// Comprehensive Anatomy Database from Climber's Study Guide
// Real images from TeachMeAnatomy (verified working)

const IMAGES = {
    forearm: 'https://teachmeanatomy.info/wp-content/uploads/Deep-Flexor-Muscles-of-the-Anterior-Forearm-1024x355.png',
    forearm_superficial: 'https://teachmeanatomy.info/wp-content/uploads/Superficial-Flexor-Muscles-of-the-Anterior-Forearm.png',
    back: 'https://teachmeanatomy.info/wp-content/uploads/Superficial-Muscles-of-the-Back-857x1024.jpg',
    arm: 'https://teachmeanatomy.info/wp-content/uploads/Coracobrachialis-Biceps-and-Brachialis-Muscles.jpg',
    triceps: 'https://teachmeanatomy.info/wp-content/uploads/Long-and-Lateral-Heads-of-the-Triceps-Brachii.jpg',
    shoulder: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Arm_muscles_front_deep.png/300px-Arm_muscles_front_deep.png',
    hand: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Hand_dissection_1.jpg/300px-Hand_dissection_1.jpg'
};

const ANATOMY_DB = [
    // === THE BACK ===
    {
        id: 'lat',
        name: 'Latissimus Dorsi',
        latin: 'Musculus latissimus dorsi',
        region: 'Back',
        image: IMAGES.back,
        credit: 'TeachMeAnatomy',
        origin: 'Spinous processes T7–T12, thoracolumbar fascia, iliac crest, inferior 3–4 ribs, inferior angle of scapula',
        insertion: 'Floor of the intertubercular (bicipital) groove of the humerus',
        nerve: 'Thoracodorsal nerve (C6, C7, C8) — posterior cord of brachial plexus',
        artery: 'Thoracodorsal artery (branch of subscapular artery)',
        actions: 'Extension, adduction, and medial rotation of shoulder; assists forced expiration',
        climbingCue: 'Pay attention to <strong>lat engagement on every pull-down</strong>. Feel the connection from hands to hips. When your mid-back fatigues on a sustained route, that\'s your lat approaching failure.',
        climbingDetail: 'The primary pulling muscle. Every pull-down on a hold is powered by the lats. Dominant on steep overhangs and during lock-off positions.',
        clinical: 'Thoracodorsal nerve at risk during axillary lymph node dissection. Damage → weakness pushing on armrests to stand. Also used as muscle flap in breast reconstruction.'
    },
    {
        id: 'trapezius',
        name: 'Trapezius',
        latin: 'Musculus trapezius',
        region: 'Back',
        image: IMAGES.back,
        credit: 'TeachMeAnatomy',
        origin: 'Medial 1/3 superior nuchal line, EOP, ligamentum nuchae, spinous processes C7–T12',
        insertion: 'Lateral 1/3 clavicle, acromion, spine of scapula',
        nerve: 'Motor: Spinal accessory nerve (CN XI). Proprioception: C3, C4 ventral rami',
        artery: 'Transverse cervical artery (thyrocervical trunk)',
        actions: 'Upper fibers: elevate scapula. Middle: retract. Lower: depress. All: upward rotation of glenoid.',
        climbingCue: 'Pay attention to <strong>trap fibers during different moves</strong>. Upper fibers shrug during top-outs. Lower fibers keep shoulders packed during dead-hangs. Middle fibers retract during lock-offs.',
        climbingDetail: 'Stabilizes scapula throughout every climbing movement. Upper fibers often overactive in climbers — work on engaging lower fibers.',
        clinical: 'CN XI is superficial in posterior triangle of neck — vulnerable during lymph node biopsy. Damage → cannot shrug, difficulty abducting past 90°.'
    },
    {
        id: 'rhomboids',
        name: 'Rhomboid Major & Minor',
        latin: 'Musculi rhomboidei',
        region: 'Back',
        image: IMAGES.back,
        credit: 'TeachMeAnatomy',
        origin: 'Minor: ligamentum nuchae, C7–T1. Major: T2–T5 spinous processes',
        insertion: 'Medial border of scapula (minor at root of spine; major below spine to inferior angle)',
        nerve: 'Dorsal scapular nerve (C5) — pierces middle scalene',
        artery: 'Dorsal scapular artery',
        actions: 'Retract scapula, inferior rotation of glenoid, stabilize scapula to thoracic wall',
        climbingCue: 'Pay attention to <strong>rhomboids when squeezing shoulder blades together</strong> at the bottom of a pull. Essential for lock-off scapular stability.',
        climbingDetail: 'Fire when you squeeze shoulder blades together. Engage most during slow, controlled descents and lock-offs.',
        clinical: 'Dorsal scapular nerve pierces middle scalene — entrapment mimics cervical radiculopathy with medial scapular pain. Causes medial winging (distinct from serratus/lateral winging).'
    },
    {
        id: 'serratus',
        name: 'Serratus Anterior',
        latin: 'Musculus serratus anterior',
        region: 'Thorax',
        image: IMAGES.back,
        credit: 'TeachMeAnatomy',
        origin: 'External surfaces of ribs 1–8, via fleshy digitations',
        insertion: 'Costal surface of medial border and inferior angle of scapula',
        nerve: 'Long thoracic nerve (C5, C6, C7) — descends superficially on muscle along midaxillary line',
        artery: 'Lateral thoracic artery, superior thoracic artery, thoracodorsal artery',
        actions: 'Protraction of scapula, upward rotation of glenoid, holds scapula to chest wall',
        climbingCue: 'Pay attention to <strong>serratus when reaching far or mantling</strong>. Feel the lateral rib activation as your scapula pushes forward. The "boxer\'s muscle."',
        climbingDetail: 'Fires every time you reach for a distant hold or push upward. Without adequate serratus function, scapula would wing off chest wall under load.',
        clinical: 'Long thoracic nerve runs superficially — vulnerable during mastectomy, chest tube insertion. Damage → classic winged scapula when pushing against wall. High-yield board question.'
    },
    {
        id: 'levator',
        name: 'Levator Scapulae',
        latin: 'Musculus levator scapulae',
        region: 'Neck/Back',
        image: IMAGES.back,
        credit: 'TeachMeAnatomy',
        origin: 'Transverse processes C1–C4 (posterior tubercles)',
        insertion: 'Superior angle and medial border of scapula (above spine)',
        nerve: 'Dorsal scapular nerve (C5) and direct branches from C3, C4',
        artery: 'Dorsal scapular artery, ascending cervical artery',
        actions: 'Elevation of scapula, inferior rotation of glenoid, lateral flexion of cervical spine',
        climbingCue: 'Pay attention to <strong>levator scapulae tension during reaching</strong>. Often becomes tight and overworked in climbers who carry neck tension. Common source of post-climbing stiffness.',
        climbingDetail: 'Stabilizes superior angle during pulling. Develops myofascial trigger points at insertion on superior angle.',
        clinical: 'Common source of neck/upper shoulder pain and tension headaches. Shares dorsal scapular nerve with rhomboids.'
    },

    // === SHOULDER & ROTATOR CUFF ===
    {
        id: 'supraspinatus',
        name: 'Supraspinatus',
        latin: 'Musculus supraspinatus',
        region: 'Shoulder (Rotator Cuff)',
        image: IMAGES.shoulder,
        credit: 'Wikimedia Commons',
        origin: 'Supraspinous fossa of scapula',
        insertion: 'Superior facet of greater tubercle of humerus; blends with superior capsule',
        nerve: 'Suprascapular nerve (C5, C6) — through suprascapular notch under superior transverse scapular ligament',
        artery: 'Suprascapular artery (thyrocervical trunk) — passes OVER the ligament',
        actions: 'Initiates abduction (first 0–15°), stabilizes humeral head in glenoid',
        climbingCue: 'Pay attention to <strong>supraspinatus when initiating any reach</strong>. It centers the humeral head during pulling and reaching. Most commonly injured rotator cuff muscle in climbers.',
        climbingDetail: 'Works constantly to center humeral head during pulling and reaching. Critical zone ~1cm proximal to insertion has watershed hypovascularity.',
        clinical: 'Most commonly torn rotator cuff tendon. Empty can test (Jobe): arm 90° abduction, 30° forward flexion, thumb down, resist downward pressure.'
    },
    {
        id: 'infraspinatus',
        name: 'Infraspinatus',
        latin: 'Musculus infraspinatus',
        region: 'Shoulder (Rotator Cuff)',
        image: IMAGES.back,
        credit: 'TeachMeAnatomy',
        origin: 'Infraspinous fossa of scapula',
        insertion: 'Middle facet of greater tubercle of humerus',
        nerve: 'Suprascapular nerve (C5, C6) — after passing through spinoglenoid notch',
        artery: 'Suprascapular artery and circumflex scapular artery',
        actions: 'Lateral (external) rotation of shoulder, posterior stabilization of humeral head',
        climbingCue: 'Pay attention to <strong>infraspinatus during gastons</strong>. External rotation engages it. Essential for decelerating dynamic moves (dynos). Key stabilizer preventing anterior dislocation.',
        climbingDetail: 'Fires during gastons. Works as force couple with subscapularis — centering humeral head in glenoid.',
        clinical: 'Ganglion cyst at spinoglenoid notch selectively denervates infraspinatus, sparing supraspinatus. Presents as isolated lateral rotation weakness.'
    },
    {
        id: 'subscapularis',
        name: 'Subscapularis',
        latin: 'Musculus subscapularis',
        region: 'Shoulder (Rotator Cuff)',
        image: IMAGES.shoulder,
        credit: 'Wikimedia Commons',
        origin: 'Subscapular fossa (entire anterior/costal surface of scapula)',
        insertion: 'Lesser tubercle of humerus and transverse humeral ligament',
        nerve: 'Upper and lower subscapular nerves (C5, C6, C7) — posterior cord',
        artery: 'Subscapular artery (largest branch of 3rd part axillary)',
        actions: 'Medial (internal) rotation, adduction, anterior stabilization of humeral head',
        climbingCue: 'Pay attention to <strong>subscapularis during cross-body moves and arm locks</strong>. Largest rotator cuff muscle. Powers internal rotation and prevents anterior humeral translation during every pull.',
        climbingDetail: 'Largest and strongest rotator cuff muscle. ONLY rotator cuff on lesser tubercle (all others on greater tubercle).',
        clinical: 'Lift-off test (Gerber): hand behind back, lift off. Belly press test: press hand against abdomen. Transverse humeral ligament holds long head biceps in groove.'
    },
    {
        id: 'deltoid',
        name: 'Deltoid',
        latin: 'Musculus deltoideus',
        region: 'Shoulder',
        image: IMAGES.shoulder,
        credit: 'Wikimedia Commons',
        origin: 'Anterior: lateral 1/3 clavicle. Middle: acromion. Posterior: scapular spine.',
        insertion: 'Deltoid tuberosity on lateral humeral shaft',
        nerve: 'Axillary nerve (C5, C6) — through quadrilateral space, wraps around surgical neck',
        artery: 'Posterior circumflex humeral artery, thoracoacromial artery (deltoid branch)',
        actions: 'Anterior: flexion/medial rotation. Middle: abduction 15–90°. Posterior: extension/lateral rotation.',
        climbingCue: 'Pay attention to <strong>deltoid during top-outs and gastons</strong>. Middle deltoid powers upward push. Posterior deltoid for gastons. Anterior for front-reaching.',
        climbingDetail: 'Primary mover for abduction past 15°. Origin mirrors trapezius insertion — continuous superficial sheet.',
        clinical: 'Surgical neck fractures or anterior dislocations → axillary nerve injury → deltoid paralysis + "regimental badge" anesthesia. Always test sensation before reducing dislocations.'
    },

    // === THE ARM ===
    {
        id: 'biceps',
        name: 'Biceps Brachii',
        latin: 'Musculus biceps brachii',
        region: 'Arm (Anterior)',
        image: IMAGES.arm,
        credit: 'TeachMeAnatomy',
        origin: 'Long head: supraglenoid tubercle (intracapsular). Short head: coracoid process (with coracobrachialis).',
        insertion: 'Radial tuberosity + bicipital aponeurosis (lacertus fibrosus) into forearm fascia',
        nerve: 'Musculocutaneous nerve (C5, C6)',
        artery: 'Brachial artery (muscular branches)',
        actions: 'Supination (most powerful when elbow 90°), elbow flexion (secondary to brachialis), weak shoulder flexion',
        climbingCue: 'Pay attention to <strong>biceps on sidepulls and underlings</strong>. Stronger supinator than flexor — feel it engage twisting. Long head can develop impingement in bicipital groove.',
        climbingDetail: 'Fires with every lock-off. Aponeurosis connects to forearm flexor fascia; tendon wraps around radius for supination.',
        clinical: 'Bicipital aponeurosis protects brachial artery + median nerve in cubital fossa. Long head rupture → "Popeye deformity." Speed\'s test for tendinopathy.'
    },
    {
        id: 'brachialis',
        name: 'Brachialis',
        latin: 'Musculus brachialis',
        region: 'Arm (Anterior)',
        image: IMAGES.arm,
        credit: 'TeachMeAnatomy',
        origin: 'Distal half of anterior humeral surface, medial and lateral intermuscular septa',
        insertion: 'Coronoid process and tuberosity of ulna',
        nerve: 'Musculocutaneous nerve (C5, C6) primary; lateral portion also radial nerve (C7) — dual innervation',
        artery: 'Brachial artery, radial recurrent artery',
        actions: 'Elbow flexion — primary flexor regardless of forearm position',
        climbingCue: 'Pay attention to <strong>brachialis during lock-offs</strong>. True workhorse of elbow flexion. Works equally in pronation, supination, or neutral. Feel the deep anterior arm burn.',
        climbingDetail: 'More important than biceps! Inserts on ulna (doesn\'t rotate), so force independent of forearm position. Forms floor of cubital fossa.',
        clinical: 'Dual nerve supply ensures flexion preserved with single nerve injury. Musculocutaneous continues as lateral cutaneous nerve of forearm.'
    },
    {
        id: 'triceps',
        name: 'Triceps Brachii',
        latin: 'Musculus triceps brachii',
        region: 'Arm (Posterior)',
        image: IMAGES.triceps,
        credit: 'TeachMeAnatomy',
        origin: 'Long head: infraglenoid tubercle. Lateral head: above radial groove. Medial head: below radial groove.',
        insertion: 'Olecranon process of ulna',
        nerve: 'Radial nerve (C6, C7, C8) — each head gets own branch',
        artery: 'Deep brachial (profunda brachii) artery — travels with radial nerve in radial groove',
        actions: 'Elbow extension (all heads). Long head: shoulder extension and adduction.',
        climbingCue: 'Pay attention to <strong>triceps during mantling and pressing</strong>. Powers top-outs. Decelerates elbow flexion eccentrically. Long head assists lats in shoulder extension.',
        climbingDetail: 'Long head passes between teres major and teres minor creating quadrilateral space boundaries. Olecranon bursa overlies insertion.',
        clinical: 'Radial nerve + profunda brachii in radial groove. Midshaft humeral fracture → wrist drop, loss of brachioradialis reflex, sensory loss in snuffbox. Triceps usually spared (branches arise proximal).'
    },

    // === FOREARM ===
    {
        id: 'fdp',
        name: 'Flexor Digitorum Profundus',
        latin: 'Musculus FDP',
        region: 'Forearm (Deep)',
        image: IMAGES.forearm,
        credit: 'TeachMeAnatomy',
        origin: 'Proximal 3/4 anterior ulna, interosseous membrane',
        insertion: 'Bases of distal phalanges digits 2–5',
        nerve: 'Lateral (digits 2,3): anterior interosseous nerve. Medial (digits 4,5): ulnar nerve (C8, T1).',
        artery: 'Anterior interosseous artery, ulnar artery',
        actions: 'Flexion of DIP joints — ONLY muscle that flexes DIP. Also assists PIP, MCP, and wrist flexion.',
        climbingCue: 'Pay attention to <strong>FDP when crimping</strong>. The final fingertip curl. Feel the deep forearm burn as you curl onto small edges. Tendons give rise to lumbricals.',
        climbingDetail: 'Only muscle that flexes DIP — the crimp engine. Only forearm flexor originating entirely from ulna (not medial epicondyle). Passes through FDS split (chiasm of Camper).',
        clinical: 'Anterior interosseous syndrome (Kiloh-Nevin): AIN is pure motor, no sensory loss. Cannot make "OK" sign (FDP index + FPL lost). Split innervation reflects embryological boundary.'
    },
    {
        id: 'fds',
        name: 'Flexor Digitorum Superficialis',
        latin: 'Musculus FDS',
        region: 'Forearm (Intermediate)',
        image: IMAGES.forearm_superficial,
        credit: 'TeachMeAnatomy',
        origin: 'Humeroulnar head: medial epicondyle + coronoid. Radial head: superior half anterior radius.',
        insertion: 'Sides of middle phalanges digits 2–5. Each tendon splits (chiasm of Camper) to let FDP through.',
        nerve: 'Median nerve (C7, C8, T1)',
        artery: 'Ulnar artery, anterior interosseous artery',
        actions: 'Flexion of PIP joints digits 2–5. Assists MCP and wrist flexion.',
        climbingCue: 'Pay attention to <strong>FDS on slopers and open-hand grips</strong>. Flexes PIP. Test in isolation: hold other fingers extended, flex one PIP.',
        climbingDetail: 'Crucial for open-hand grips. Median nerve and ulnar artery pass deep to FDS arch entering forearm.',
        clinical: 'FDS splits for FDP (chiasm of Camper). Test: hold all other fingers extended, flex PIP. FDS to 5th digit absent/weak in ~20%.'
    },

    // === HAND ===
    {
        id: 'lumbricals',
        name: 'Lumbricals',
        latin: 'Musculi lumbricales',
        region: 'Hand (Intrinsic)',
        image: IMAGES.hand,
        credit: 'Wikimedia Commons',
        origin: '1st/2nd: radial side FDP tendons digits 2,3 (unipennate). 3rd/4th: adjacent FDP tendons (bipennate).',
        insertion: 'Lateral (radial) side of extensor expansion digits 2–5',
        nerve: '1st/2nd: median nerve. 3rd/4th: deep branch ulnar nerve (C8, T1).',
        artery: 'Common and proper palmar digital arteries (superficial palmar arch)',
        actions: 'Flex MCP + extend PIP and DIP simultaneously — the unique "lumbrical position."',
        climbingCue: 'Pay attention to <strong>lumbricals on slopers and half-crimp</strong>. Enable open-hand grip: MCP flexion + IP extension maximizes contact area.',
        climbingDetail: 'Unique: arise from tendons (FDP), insert into tendons (extensor expansion) — no bony attachment. Only muscles simultaneously flexing MCP and extending IP.',
        clinical: 'Lumbrical shift injury: differential FDP loading pulls lumbrical into carpal tunnel. Split innervation mirrors FDP split. Loss contributes to "hand of benediction."'
    },
    {
        id: 'interossei',
        name: 'Dorsal & Palmar Interossei',
        latin: 'Musculi interossei',
        region: 'Hand (Intrinsic)',
        image: IMAGES.hand,
        credit: 'Wikimedia Commons',
        origin: 'Dorsal (4): adjacent sides of two MCs (bipennate). Palmar (3-4): single MC (unipennate).',
        insertion: 'Proximal phalanx bases and lateral bands of extensor expansions',
        nerve: 'Deep branch of ulnar nerve (C8, T1) — ALL interossei',
        artery: 'Deep palmar arch, palmar and dorsal metacarpal arteries',
        actions: 'Dorsal: ABduction (DAB). Palmar: ADduction (PAD). Both flex MCP and extend IP via extensor expansion.',
        climbingCue: 'Pay attention to <strong>interossei for finger spread and squeeze</strong>. DAB = Dorsal ABduct (spread for wide holds). PAD = Palmar ADduct (squeeze for cracks/pockets).',
        climbingDetail: 'First dorsal interosseous most clinically tested (first web space). MCP flexion + IP extension crucial for open-hand grip.',
        clinical: 'Low ulnar lesion → claw hand (4th/5th hyperextend MCP, flex IP). Ulnar paradox: HIGH lesion = LESS clawing (FDP 4,5 also lost). Froment\'s sign for adductor pollicis.'
    },
    {
        id: 'pulleys',
        name: 'Flexor Pulley System (A2/A4)',
        latin: 'Vagina fibrosa digitorum manus',
        region: 'Hand (Finger)',
        image: IMAGES.hand,
        credit: 'Wikimedia Commons',
        origin: 'A1: MCP volar plate. A2: proximal phalanx. A3: PIP joint. A4: middle phalanx. A5: DIP joint.',
        insertion: 'N/A — fibrous sheaths constraining flexor tendons to phalanges',
        nerve: 'N/A (non-contractile connective tissue). Vinculae carry blood vessels to tendons.',
        artery: 'Digital arteries supply vinculae which vascularize flexor tendons',
        actions: 'Prevent bowstringing — hold tendons close to bone for efficient force conversion',
        climbingCue: 'Pay attention to <strong>pulley stress when full crimping</strong>. A2 and A4 are biomechanically critical. Consider half-crimp or open-hand to reduce strain.',
        climbingDetail: 'THE most clinically relevant structure for climbing injuries. Pulley ruptures (especially A2) from aggressive crimping — "pop" felt, followed by swelling.',
        clinical: 'A2 + A4 most important biomechanically. Combined rupture may need surgical reconstruction. A1 pathology → trigger finger. Flexor tenosynovitis: Kanavel signs = surgical emergency.'
    },
    {
        id: 'thenar',
        name: 'Thenar Muscles',
        latin: 'Opponens pollicis, APB, FPB',
        region: 'Hand (Thenar)',
        image: IMAGES.hand,
        credit: 'Wikimedia Commons',
        origin: 'Flexor retinaculum, trapezium, scaphoid. Deep head FPB: trapezoid + capitate.',
        insertion: 'Opponens: 1st MC shaft. APB: lateral proximal phalanx thumb. FPB: proximal phalanx base.',
        nerve: 'Recurrent branch of median nerve (C8, T1) — "million dollar nerve." Deep head FPB by deep ulnar.',
        artery: 'Superficial palmar branch of radial artery, princeps pollicis artery',
        actions: 'Opposition (opponens), thumb abduction (APB), thumb MCP flexion (FPB). Together enable pincer grip.',
        climbingCue: 'Pay attention to <strong>thenar muscles during every pinch grip</strong>. Feel the thenar eminence contract forcefully. Opposition brings thumb pad to face finger pads.',
        climbingDetail: 'Essential for every pinch grip. Recurrent branch emerges laterally from median nerve just distal to retinaculum.',
        clinical: 'Recurrent branch laceration destroys opposition — profound disability. "Ape hand" = thenar wasting + loss of opposition. Test: touch thumb tip to 5th finger tip.'
    }
];

export { ANATOMY_DB, IMAGES };
